"""Assemble the scattered section files into one readable manuscript.

The manuscript is drafted in pieces so each section can sit next to the analysis
that produced it. That is good for provenance and bad for reading. This script
stitches the pieces into `MANUSCRIPT.md` in reading order and drops the
internal-record material — filenames, defect history, verification tables,
reviewer-facing asides — which belongs in the repo, not the paper.

Run it after editing any section file:

    python assemble_manuscript.py

It fails loudly if a section marker has moved, rather than silently emitting a
truncated manuscript.
"""

from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "MANUSCRIPT.md"

# (file, start marker, end marker or None for end-of-file, heading override)
SECTIONS = [
    ("MANUSCRIPT_ABSTRACT_CONCLUSIONS.md", "## Abstract",
     "**Candidate result sentence for the body**", None),
    ("MANUSCRIPT_INTRODUCTION.md", "## 1. Introduction",
     "## Citation notes and verification status", None),
    ("MANUSCRIPT_METHODS.md", "## 2. Experiment and instrumentation",
     "## Remaining Methods subsections", None),
    ("DEEP_DVV_METHODS_DRAFT.md", "### Observable and split-sample selection",
     "## Results", "### 3.13 Deep observable, estimator and calibration"),
    ("MANUSCRIPT_RESULTS.md", "## 4.1 Installation dependence",
     "## Cross-references for the remaining Results sections", None),
    ("DEEP_DVV_METHODS_DRAFT.md", "### Calibrated sensitivity",
     "## Manuscript-ready summary paragraph",
     "## 4.6 Deep sensitivity, paired legs and the Nano comparison"),
    ("MANUSCRIPT_DISCUSSION.md", "## 5.1 Why the two installations",
     None, None),
    ("MANUSCRIPT_ABSTRACT_CONCLUSIONS.md", "## 6. Conclusions",
     "## Interpretation limits carried into the conclusions", None),
    ("MANUSCRIPT_ABSTRACT_CONCLUSIONS.md",
     "## Interpretation limits carried into the conclusions",
     "## Outstanding before submission", None),
]

PREAMBLE = """# Contrasting Borehole DAS Installations at SAFOD: Wavefield Observability and Monitoring Sensitivity

**Assembled draft — generated by `assemble_manuscript.py`. Do not edit this file;
edit the section sources and re-run.**

Section sources, in order: `MANUSCRIPT_ABSTRACT_CONCLUSIONS.md`,
`MANUSCRIPT_INTRODUCTION.md`, `MANUSCRIPT_METHODS.md`,
`DEEP_DVV_METHODS_DRAFT.md`, `MANUSCRIPT_RESULTS.md`,
`MANUSCRIPT_DISCUSSION.md`.

What was run to produce every number: [`REPRODUCE.md`](REPRODUCE.md).
Frozen analysis design: [`DEEP_DVV_PREREGISTRATION.md`](DEEP_DVV_PREREGISTRATION.md).
Authoritative claim table: [`DEEP_DVV_STATUS.md`](DEEP_DVV_STATUS.md).

---

"""


def extract(filename: str, start: str, end: str | None) -> str:
    path = HERE / filename
    text = path.read_text()
    if start not in text:
        raise SystemExit(f"marker missing in {filename}: {start!r}")
    body = text[text.index(start):]
    if end is not None:
        if end not in body:
            raise SystemExit(f"end marker missing in {filename}: {end!r}")
        body = body[:body.index(end)]
    return body.rstrip()


def main() -> None:
    parts = [PREAMBLE]
    for filename, start, end, heading in SECTIONS:
        body = extract(filename, start, end)
        if heading is not None:
            # Replace the source's own first heading with the manuscript's
            first_newline = body.index("\n")
            body = heading + body[first_newline:]
        parts.append(body)
        parts.append("\n\n---\n\n")
    OUT.write_text("\n".join(parts).rstrip() + "\n")
    words = len(OUT.read_text().split())
    print(f"wrote {OUT.name}: {len(SECTIONS)} sections, ~{words:,} words")


if __name__ == "__main__":
    main()
