"""Promote the single SAFOD dashboard notebook to v3.

The script makes only text/cell-structure changes; all numerical products are
generated by the versioned scripts in this directory and loaded by the
notebook.  It is kept as an auditable promotion step so the notebook version
cannot silently drift from the status registry.
"""
from pathlib import Path
import json

P = Path(__file__).resolve().parent / "AWD_results_dashboard.ipynb"
d = json.loads(P.read_text())

def src(cell):
    return "".join(cell.get("source", []))

def md(text):
    return {"cell_type":"markdown", "metadata":{}, "source":text.splitlines(True)}

def code(text):
    return {"cell_type":"code", "execution_count":None, "metadata":{},
            "outputs":[], "source":text.splitlines(True)}

# Version cell is intentionally minimal, as requested.
for cell in d["cells"]:
    if src(cell).strip() in {"v2", "v2-candidate", "v3"}:
        cell["cell_type"] = "markdown"
        cell["source"] = ["v3\n"]
        cell["metadata"] = {}

for cell in d["cells"]:
    s = src(cell)
    if s.startswith("## Current status registry"):
        cell["source"] = """## Current status registry

*Status flags last synchronized: 2 August 2026; dashboard promotion v3.*

| Result | Flag | Current basis |
|---|---|---|
| Experiment reconstruction | **Accepted** | 49 bursts, 988 drops, 859 complete paired windows |
| Catalog timing for relative alignment | **Accepted** | Catalog is a PEG500 cross-correlation arrival pick; absolute impact time remains uncalibrated |
| Nano coherent mode | **Accepted** | Visible ordered ridge; permutation \\(p=0.002\\); pre-source maximum 0.043 |
| Nano apparent velocity and direction | **Accepted as apparent mode properties** | 2.95–2.99 km s⁻¹; positive signed slowness |
| Individual-drop repeatability | **Accepted** | 988 drops; signal NCC median 0.889 versus noise 0.288; median beam SNR 7.72 dB |
| Within-burst repeatability | **Accepted** | 49/49 bursts have signal NCC above noise; exact one-sided sign-test \\(p=1.78\\times10^{-15}\\) |
| Across-burst repeatability | **Accepted** | Leave-one-burst-out NCC median 0.976; median delay −0.048 ms |
| Nano frequency observability | **Accepted at burst-stack level** | Median 30–60 Hz SNR remains positive through the 460 m bin |
| Nano direct-P identity | **Unresolved** | SAFOD-model forward test is now available; observed data still admit direct-P and guided explanations |
| Deep full-leg stationary mode | **Inconclusive** | Full-leg coherence remains below threshold |
| Deep 1.4–1.56 km s⁻¹ low-frequency mode | **Accepted as a repeatable signed-slowness mode** | Odd/even split and four fixed-p permutation tests give \\(p=0.002\\) |
| Deep tube-wave interpretation | **Preliminary** | Consistent velocity and down-going wavefield; no unique conversion depth |
| SAFOD-model forward comparison | **Preliminary sensitivity test** | 3-D Vp/Vs/Vp/Vs prior parsed; direct-P and guided synthetic observables compared |
| Blind apparent-moveout detection limit | **Accepted at observable level** | 95% null threshold 0.00325; tested 95%-correct-sign level 0.01 |
| Earth-tide-scale observability | **Benchmark only** | Illustrative 5×10⁻⁴ target remains above the present one-day threshold |
| Geological \\(V_P\\) profile | **Not claimed** | Requires phase identification, geometry calibration, and a formal inversion |
| Permeability or hydraulic-fracture inference | **Not claimed** | Requires physical-depth registration and repeatable reflection/amplitude evidence |

These flags govern the wording used in figures, captions, the evidence table, and the conclusion.\n""".splitlines(True)

# Add the guarded hierarchical repeatability product immediately after the
# existing burst-level stability figure/caption.
insert_after = None
for i, cell in enumerate(d["cells"]):
    if src(cell).startswith("**Figure 10. Burst-to-burst stability"):
        insert_after = i + 1
        break
if insert_after is not None and not any("Hierarchical individual-drop repeatability" in src(c) for c in d["cells"]):
    d["cells"][insert_after:insert_after] = [
        md("""### Hierarchical individual-drop and burst repeatability — accepted\n\n**Question.** Is the accepted Nano moveout observable stable within individual drop bursts and across the full experiment?\n\n**Method.** The analysis extracts 988 individual drops from 49 bursts, aligns each drop only to the fixed 30–60 Hz, 80–440 m moveout trajectory, and compares normalized cross-correlation (NCC) in a signal window with an equal-duration pre-signal noise window. Leave-one-burst-out templates provide an independent across-burst check. Independent within-burst substacks test how rapidly repeatability improves with the number of drops.\n\n**Answer.** Signal NCC exceeds noise NCC in all 49 bursts (exact one-sided sign test \\(p=1.78\\times10^{-15}\\)); the median signal NCC is 0.889 versus 0.288 for noise. Leave-one-burst-out NCC has median 0.976, with median delay −0.048 ms. These are repeatability results for a phase-neutral moveout beam, not evidence that the mode is direct P or that absolute source amplitude is calibrated.\n"""),
        code("""show_image('nano_hierarchical_repeatability.png')\nprint((HERE/'nano_hierarchical_repeatability.txt').read_text())\n"""),
        md("""**Figure 12. Hierarchical repeatability of the Nano AWD moveout observable across individual drops and bursts.** (a) Within-burst signal normalized cross-correlation (NCC) for the 988 extracted drops is compared with an equal-duration pre-signal noise window; each point is one drop and the horizontal summaries show the 16th, 50th, and 84th percentiles. (b) The corresponding leave-one-out burst-template NCC quantifies stability after removing all drops from the tested burst, thereby separating across-burst consistency from within-burst averaging. (c) Within-burst substack convergence reports independent-substack NCC as a function of drops per substack; medians and central 68% intervals are shown only for stack sizes represented by at least ten bursts. (d) The analogous beam signal-to-noise summary is plotted with the same minimum-burst guard. (e–f) Drop delays and relative amplitudes are shown as distributions rather than absolute calibrations. The analysis uses the fixed 30–60 Hz, 80–440 m Nano trajectory and literal catalog alignment times; it establishes repeatability of the selected apparent-moveout observable, not a direct-P phase identification, formation (V_P), or absolute source radiation.\n""")
    ]

# Replace the conditional/planned sections with the completed forward and
# sensitivity branches, each followed immediately by its figure caption.
start = next(i for i,c in enumerate(d["cells"]) if src(c).startswith("## 10. Conditional"))
end = next(i for i,c in enumerate(d["cells"]) if src(c).startswith("## 12. Current evidence table"))
new = [
    md("""## 10. SAFOD-model direct-P versus guided-mode forward test — preliminary\n\n### Question\nCan the transferred SAFOD 3-D velocity model predict the observed Nano moveout as a formation-controlled direct P wave, and how different would a guided-mode explanation look?\n\n### Method\n`Vp_model.dat`, `Vs_model.dat`, `Vpvs_model.dat`, `MOD.head`, and `inversion_grid.dat` are parsed as the Zhang–Thurber–Bedrosian SAFOD-centered grid. Slowness is integrated along representative shallow straight source–receiver paths. A synthetic DAS operator then generates two transparent alternatives: direct-P moveout from the model and a weakly dispersive guided curve anchored near the observed Nano ridge. The synthetic sections are displayed alongside the observed frequency-dependent apparent speeds.\n\n### Answer\nThe SAFOD prior predicts a median direct-P path speed of approximately 4.14 km s⁻¹ for the representative path used here, above the observed 2.95–2.99 km s⁻¹ ridge. This mismatch does not reject direct P because source position, receiver geometry, anisotropy, and the path used here are simplified; it does show that the observed apparent speed cannot be called a (V_P) value without geometry-calibrated ray tracing. The guided alternative remains viable.\n\n### Limitation\nThis is a sensitivity and identifiability test, not a (V_P) inversion or a full elastic simulation.\n"""),
    code("""show_image('safod_forward_model.png')\nprint((HERE/'safod_forward_model.txt').read_text())\n"""),
    md("""**Figure 13. SAFOD-model forward comparison of direct-P and guided-mode hypotheses for the Nano AWD observation.** (A) A vertical slice through the transferred Zhang–Thurber–Bedrosian (V_P) prior is shown in the model coordinate system; the dashed line marks the representative shallow source depth used for the sensitivity calculation. (B) The synthetic direct-P section is generated by integrating (1/V_P) along straight paths from a representative source to 80–500 m along-fiber offsets. (C) A deliberately low-parameter, weakly dispersive guided-mode alternative is shown using (c(f)=2.72+0.004(f-20)) km s⁻¹; this curve is a hypothesis anchored near the observed ridge, not an asserted tube-wave law. (D) Observed Nano apparent speeds and bootstrap intervals are compared with the model-derived direct-P median and guided sensitivity curve. The direct-P path speed exceeds the observed approximately 3 km s⁻¹ value for this simplified geometry; that difference motivates, but does not by itself justify, a more complete geometry- and anisotropy-aware calculation. The figure therefore answers an identifiability question—whether a plausible geological prior automatically predicts the observed ridge—rather than reporting an inversion result.\n"""),
    md("""## 11. Monitoring sensitivity versus stack size — accepted observable-level result\n\n### Question\nHow does repeated stacking change the smallest apparent-moveout perturbation that can be detected?\n\n### Method\nThe existing blind injection–recovery null distribution is used to estimate the baseline uncertainty. A transparent \\(1/\\sqrt{N}\\) independence-scaling model projects 95% null and approximate 95% power thresholds for (N=1,2,4,8,16,32,46) independent stacks. The empirical within-burst NCC convergence curve is shown beside the projected threshold.\n\n### Answer\nThe baseline null standard deviation is 0.00175 in fractional apparent moveout. Under the stated independence model, the threshold decreases with stack size, but the illustrative (5\\times10^{-4}) Earth-tide benchmark remains below the present one-day threshold even at the largest projected stack. This is a monitoring-design result for the accepted Nano apparent-moveout observable, not a direct formation \\(\\Delta V_P/V_P\\) limit.\n\n### Limitation\nThe projected curves assume independent stacks and therefore must be replaced by new blind injections when a specific monitoring schedule is proposed.\n"""),
    code("""show_image('monitoring_sensitivity.png')\nprint((HERE/'monitoring_sensitivity.txt').read_text())\n"""),
    md("""**Figure 14. Stack-size dependence of Nano AWD monitoring sensitivity.** (A) The solid curve is the two-sided 95% null threshold obtained from the measured zero-injection distribution and scaled as (1/\\sqrt{N}); the dashed curve is an approximate 95%-correct-sign power threshold using the corresponding normal approximation. The dotted line is an illustrative (5\\times10^{-4}) Earth-tide-scale benchmark, included as a physical comparison rather than a detected signal. (B) Points and central 68% intervals show the empirical normalized cross-correlation of independent within-burst substacks as the number of drops per substack increases. The two panels answer complementary monitoring questions: how statistical uncertainty could decrease under independent repetition, and how quickly the actual recorded waveform becomes repeatable. The thresholds apply only to fractional changes in the accepted Nano apparent-moveout observable; they are not a resolved formation (V_P) or tidal response.\n"""),
]
d["cells"][start:end] = new

# Refresh the evidence table and conclusion cells.
for cell in d["cells"]:
    s = src(cell)
    if s.startswith("evidence = pd.DataFrame"):
        cell["source"] = """evidence = pd.DataFrame([\n ['Correct experiment reconstruction','Accepted','49 bursts; 988 drops; 859 complete paired windows'],\n ['Real spatially ordered Nano mode','Accepted','Permutation p=0.002; pre-source max 0.043'],\n ['Nano apparent velocity','Accepted as apparent velocity','2.95–2.99 km/s across frequency bands'],\n ['Propagation direction','Accepted','Positive slowness along increasing Nano coordinate'],\n ['Individual-drop repeatability','Accepted','988 drops; signal NCC median 0.889 vs noise 0.288'],\n ['Within-burst repeatability','Accepted','49/49 bursts exceed noise; exact sign-test p=1.78e-15'],\n ['Across-burst repeatability','Accepted','Leave-one-burst-out NCC median 0.976; delay median −0.048 ms'],\n ['Direct-P identity','Unresolved','SAFOD forward test is preliminary and geometry simplified'],\n ['Deep full-leg stationary mode','Inconclusive','Coherence falls below threshold over complete legs'],\n ['Deep slow signed-slowness mode','Accepted as repeatable mode','Independent 23/23 split; four permutation tests p=0.002'],\n ['Deep tube-wave identity','Preliminary interpretation','Consistent velocity and down-going wavefield; no conversion depth'],\n ['Nano spectral observability','Accepted at burst-stack level','Median 30–60 Hz SNR > 0 dB through 460 m bin'],\n ['Apparent-moveout sensitivity','Accepted at observable level','95% null threshold 0.00325; tested 95%-correct-sign level 0.01'],\n ['Earth-tide benchmark','Comparison only','Illustrative 5e-4 target remains below current one-day threshold'],\n ['Smooth Vp profile','Not claimed','Requires geometry-calibrated phase identification and inversion'],\n], columns=['Claim','Status','Evidence or requirement'])\ndisplay(evidence.style.set_properties(subset=['Status'], **{'font-weight':'bold'}))\n""".splitlines(True)
    if s.startswith("## 14. Current conclusion"):
        cell["source"] = """## 14. Current conclusion\n\nRepeated AWD excitation produces two installation-dependent coherent observations. Cemented Nano DAS records a statistically significant positive-slowness mode with 2.95–2.99 km s⁻¹ apparent velocity, individual-drop and burst-level repeatability, and positive 30–60 Hz spectral SNR through the 460 m bin. The direct-P versus guided-mode identity remains unresolved: the SAFOD-model forward test shows that a simplified representative direct-P path predicts approximately 4.14 km s⁻¹, so the observed approximately 3 km s⁻¹ ridge cannot be relabeled as formation (V_P) without improved geometry and ray tracing. Wireline Deep DAS records a distinct 1.4–1.56 km s⁻¹ low-frequency positive-slowness mode whose velocity and down-going expression are consistent with a tube wave, but whose physical identity and conversion depth remain preliminary. Injection–recovery establishes a detection threshold for the accepted Nano apparent-moveout observable; the illustrative Earth-tide benchmark is not resolved by the present one-day experiment. No geological (V_P) inversion or permeability inference is claimed.\n""".splitlines(True)

P.write_text(json.dumps(d, indent=1) + "\n")
print(f"Promoted {P} to v3 with {len(d['cells'])} cells")
