"""Assemble the scattered section files into one readable manuscript.

The manuscript is drafted in pieces so each section can sit next to the analysis
that produced it. That is good for provenance and bad for reading. This script
stitches the pieces into `MANUSCRIPT.md` in reading order and drops the
internal-record material — filenames, defect history, verification tables,
reviewer-facing asides — which belongs in the repo, not the paper.

Run it after editing any section file:

    python assemble_manuscript.py

It fails loudly if a section marker has moved, rather than silently emitting a
truncated manuscript.
"""

from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).resolve().parent
SECTION_DIR = HERE / "sections"
OUT = HERE / "MANUSCRIPT.md"

# (file, start marker, end marker or None for end-of-file, heading override)
SECTIONS = [
    # Abstract
    ("MANUSCRIPT_ABSTRACT_CONCLUSIONS.md", "## Abstract",
     "**Candidate result sentence for the body**", None),
    # 1 Introduction
    ("MANUSCRIPT_INTRODUCTION.md", "## 1. Introduction",
     "## Citation notes and verification status", None),
    # 2 Experiment, then Methods 3.1-3.2
    ("MANUSCRIPT_METHODS.md", "## 2. Experiment and instrumentation",
     "### 3.5 Source repeatability metrics", None),
    # Methods 3.3-3.4 (Deep observable and estimator)
    ("DEEP_DVV_METHODS_DRAFT.md",
     "### 3.3 Deep guided-mode identification and split-sample validation",
     "### 3.7 Blind injection–recovery: Deep", None),
    # Methods 3.5-3.6 (repeatability, Nano calibration)
    ("MANUSCRIPT_METHODS.md", "### 3.5 Source repeatability metrics",
     "## Remaining Methods subsections", None),
    # Methods 3.7-3.8 (Deep calibration, controls)
    ("DEEP_DVV_METHODS_DRAFT.md", "### 3.7 Blind injection–recovery: Deep",
     "## Results", None),
    # 4.1-4.5 Results
    ("MANUSCRIPT_RESULTS.md", "### 4.1 Installation dependence",
     "## Cross-references for the remaining Results sections", "## 4. Results\n"),
    # 4.6 Sensitivity results
    ("DEEP_DVV_METHODS_DRAFT.md",
     "#### 4.6.1 Calibrated sensitivity of all three observables",
     "## Manuscript-ready summary paragraph",
     "### 4.6 Sensitivity calibration and the Nano\u2013Deep comparison\n"),
    # 5 Discussion
    ("MANUSCRIPT_DISCUSSION.md", "### 5.1 Why the two installations", None,
     "## 5. Discussion\n"),
    # 6 Conclusions
    ("MANUSCRIPT_ABSTRACT_CONCLUSIONS.md", "## 6. Conclusions",
     "### 6.6 Interpretation limits carried into the conclusions", None),
    ("MANUSCRIPT_ABSTRACT_CONCLUSIONS.md",
     "### 6.6 Interpretation limits carried into the conclusions",
     "## Outstanding before submission", None),
]

PREAMBLE = """# Contrasting Borehole DAS Installations at SAFOD: Wavefield Observability and Monitoring Sensitivity

**Assembled draft — generated by `assemble_manuscript.py`. Do not edit this file;
edit the section sources and re-run.**

Section sources in `sections/`, in order: `MANUSCRIPT_ABSTRACT_CONCLUSIONS.md`,
`MANUSCRIPT_INTRODUCTION.md`, `MANUSCRIPT_METHODS.md`,
`DEEP_DVV_METHODS_DRAFT.md`, `MANUSCRIPT_RESULTS.md`,
`MANUSCRIPT_DISCUSSION.md`.

What was run to produce every number: [`REPRODUCE.md`](REPRODUCE.md).
Frozen analysis design: [`DEEP_DVV_PREREGISTRATION.md`](DEEP_DVV_PREREGISTRATION.md).
Authoritative claim table: [`DEEP_DVV_STATUS.md`](DEEP_DVV_STATUS.md).

---

"""


def extract(filename: str, start: str, end: str | None) -> str:
    path = SECTION_DIR / filename
    text = path.read_text()
    if start not in text:
        raise SystemExit(f"marker missing in {filename}: {start!r}")
    body = text[text.index(start):]
    if end is not None:
        if end not in body:
            raise SystemExit(f"end marker missing in {filename}: {end!r}")
        body = body[:body.index(end)]
    return body.rstrip()


def main() -> None:
    parts = [PREAMBLE]
    for filename, start, end, heading in SECTIONS:
        body = extract(filename, start, end)
        if heading is not None:
            # Prepend a manuscript-level heading above the source's own
            body = heading + "\n" + body
        parts.append(body)
        parts.append("\n\n---\n\n")
    OUT.write_text("\n".join(parts).rstrip() + "\n")
    words = len(OUT.read_text().split())
    print(f"wrote {OUT.name}: {len(SECTIONS)} sections, ~{words:,} words")


if __name__ == "__main__":
    main()
