"""Collect the paper's figure set from the frozen analysis outputs.

The analysis scripts each write their own figure. That is the right design —
a figure is produced by the code that computed it, so it cannot drift from the
numbers — but it leaves the figures scattered under analysis names.

This script gathers them into `figures_paper/` with manuscript numbering and
writes a manifest recording which script produced each one. It does not
recompute anything; if a figure is stale, rerun the script named in the manifest
(see REPRODUCE.md for the order).

    python make_paper_figures.py

Figures that do not yet exist are reported rather than skipped silently.
"""

from __future__ import annotations

import shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent
ANALYSIS = HERE.parent          # awd_clean/, where the scripts write
OUT = HERE / "figures"

# (number, short title, source file, producing script)
FIGURES = [
    (1, "Experiment geometry and installation contrast",
     None, "NOT YET MADE — needs a geometry schematic"),
    (2, "Nano coherent fast apparent mode",
     "nano_mode_identification.png", "nano_mode_identification.py"),
    (3, "Deep slow guided mode, record sections and trajectories",
     "deep_tube_record_sections.png", "deep_tube_validation.py"),
    (4, "Independent Deep validation: split-sample and permutation",
     "deep_tube_null_tests.png", "deep_tube_validation.py"),
    (5, "Source repeatability hierarchy, drops to burst stacks",
     "fig12_repeatability_publication.png", "publication_figures_v4.py"),
    (6, "Nano blind injection–recovery",
     "nano_dvv_injection_recovery.png", "nano_dvv_injection_recovery.py"),
    (7, "Deep blind injection–recovery and the Nano–Deep comparison",
     "deep_dvv_injection_recovery.png", "deep_dvv_injection_recovery.py"),
]

SUPPLEMENT = [
    ("S1", "Deep split-sample repeatability by aperture",
     "deep_tube_repeatability.png", "deep_tube_validation.py"),
    ("S2", "Nano repeatability, full hierarchy",
     "nano_hierarchical_repeatability.png", "nano_hierarchical_repeatability.py"),
    ("S3", "Solid-Earth-tide regression, held-out bursts",
     "deep_dvv_tidal_fit.png", "deep_dvv_tidal_fit.py"),
    ("S4", "Solid-Earth-tide regression, all 46 bursts",
     "deep_dvv_tidal_fit_allbursts.png",
     "deep_dvv_tidal_fit.py --population allbursts"),
    ("S5", "Virtual source at 149 m: correlation vs deconvolution",
     "../figures/awd_2026/plain_look/virtual_source/vs_fig03_moveout_and_wiggles.png",
     "awd_virtual_source.py"),
    ("S6", "Virtual-source correlation gathers, four reference channels",
     "../figures/awd_2026/plain_look/virtual_source/vs_fig01_correlation_gathers.png",
     "awd_virtual_source.py"),
    ("S7", "Virtual-source deconvolution gathers, four reference channels",
     "../figures/awd_2026/plain_look/virtual_source/vs_fig02_deconvolution_gathers.png",
     "awd_virtual_source.py"),
]


def collect(entries, label: str, slug: str) -> tuple[list[str], list[str]]:
    rows, missing = [], []
    for number, title, source, script in entries:
        tag = f"{slug}{number:02d}" if isinstance(number, int) else str(number).lower()
        if source is None or not (ANALYSIS / source).exists():
            missing.append(f"{label}{number}: {title} — {script}")
            rows.append(f"| {label}{number} | {title} | *(missing)* | {script} |")
            continue
        target = OUT / f"{tag}_{Path(source).stem}.png"
        shutil.copy2(ANALYSIS / source, target)
        size = target.stat().st_size / 1e6
        rows.append(f"| {label}{number} | {title} | `{target.name}` ({size:.1f} MB) | `{script}` |")
    return rows, missing


def main() -> None:
    OUT.mkdir(exist_ok=True)
    for stale in OUT.glob("*.png"):   # clear prior naming before recollecting
        stale.unlink()
    main_rows, main_missing = collect(FIGURES, "Fig ", "fig")
    supp_rows, supp_missing = collect(SUPPLEMENT, "", "s")

    manifest = [
        "# Paper figure set",
        "",
        "Generated by `make_paper_figures.py`. Figures are copied from the analysis",
        "outputs, not recomputed — each was written by the script that computed its",
        "numbers. To refresh one, rerun the script named here; see `REPRODUCE.md` for",
        "the dependency order.",
        "",
        "## Main figures",
        "",
        "| # | Title | File | Produced by |",
        "|---|---|---|---|",
        *main_rows,
        "",
        "## Supplement",
        "",
        "| # | Title | File | Produced by |",
        "|---|---|---|---|",
        *supp_rows,
        "",
    ]
    if main_missing or supp_missing:
        manifest += ["## Still to make", ""]
        manifest += [f"- {m}" for m in main_missing + supp_missing]
        manifest += [""]
    (OUT / "FIGURES.md").write_text("\n".join(manifest))

    print(f"collected into {OUT.name}/")
    for m in main_missing + supp_missing:
        print(f"  MISSING  {m}")
    print(f"  manifest: {OUT.name}/FIGURES.md")


if __name__ == "__main__":
    main()
